name: build-test-pipeline

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    
jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0.x'
    
    - name: restore dependencies
      run: dotnet restore
      working-directory: src/Explore.Cli

    - name: Build
      run: |
        dotnet build src/Explore.Cli/Explore.Cli.csproj --configuration $BUILD_CONFIG

    - name: Run tests
      run: dotnet test test/Explore.Cli.Tests/Explore.Cli.Tests.csproj /p:Configuration=$env:BUILD_CONFIG --verbosity normal
