name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    
jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

   #- name: Restore dependencies
   # run: nuget restore $SOLUTION

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0.x'

    - name: Build
      run: dotnet build dotnet build src/Explore.Cli/Explore.Cli.csproj --configuration $BUILD_CONFIG --no-restore

    - name: Run tests
      run: dotnet test test/Explore.Cli.Tests/Explore.Cli.Tests.csproj /p:Configuration=$env:BUILD_CONFIG --no-restore --no-build --verbosity normal
